spring:
  application:
    name: iam-service


  config:
    import: "configserver:"

  cloud:
    config:
      uri: http://config.platform:9000

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

app:
  storage:
    path: ./uploads/customers